### ISSUE TITLE
Several issues detected when trying tower_test.py

### ISSUE THREAD

**Issue by ArnaudFickinger** [aaronwalsman/ltron#3]

**Comment by aaronwalsman** [comment]
Hey!  Thanks so much for this!  Unfortunately there are several things in
the repo right now that aren't working.  I made the whole thing public when
we talked about the data at a workshop last year so that people could
explore the files, but development has been ongoing, and there are some
false-starts in here.  Since then I've been focussed on a particular
problem in this space of learning how to reassemble an object after taking
it apart.  If you are interested in exploring the tower stuff or some other
simpler problems, I might be able to find some time to clean that up
though.  Are you a student?  ML researcher? LEGO fan?  All of the above?

-Aaron

**Comment by aaronwalsman** [comment]
Oh now that I'm on github, I see your bio.  Anyway, thanks again for posting the issue.  If you are interested in working in this space, let me know, we could get some collaboration going or something.
